[2025-04-11T03:35:16.275+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-11T03:35:16.292+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.data_storing scheduled__2025-04-10T00:00:00+00:00 [queued]>
[2025-04-11T03:35:16.301+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.data_storing scheduled__2025-04-10T00:00:00+00:00 [queued]>
[2025-04-11T03:35:16.303+0000] {taskinstance.py:2856} INFO - Starting attempt 10 of 11
[2025-04-11T03:35:16.317+0000] {taskinstance.py:2879} INFO - Executing <Task(_PythonDecoratedOperator): data_storing> on 2025-04-10 00:00:00+00:00
[2025-04-11T03:35:16.326+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1820) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-11T03:35:16.329+0000] {standard_task_runner.py:72} INFO - Started process 1826 to run task
[2025-04-11T03:35:16.328+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'data_storing', 'scheduled__2025-04-10T00:00:00+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/dag_for_workshop.py', '--cfg-path', '/tmp/tmpa5pmsdb0']
[2025-04-11T03:35:16.332+0000] {standard_task_runner.py:105} INFO - Job 53: Subtask data_storing
[2025-04-11T03:35:16.384+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_dag.data_storing scheduled__2025-04-10T00:00:00+00:00 [running]> on host c97e2588350c
[2025-04-11T03:35:16.470+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='example@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='data_storing' AIRFLOW_CTX_EXECUTION_DATE='2025-04-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='10' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-10T00:00:00+00:00'
[2025-04-11T03:35:16.471+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-11T03:35:16.473+0000] {etl.py:89} ERROR - Error storing data locally: the JSON object must be str, bytes or bytearray, not NoneType
[2025-04-11T03:35:16.474+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-11T03:35:16.482+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-11T03:35:16.483+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=data_storing, run_id=scheduled__2025-04-10T00:00:00+00:00, execution_date=20250410T000000, start_date=20250411T033516, end_date=20250411T033516
[2025-04-11T03:35:16.504+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2025-04-11T03:35:16.521+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-11T03:35:16.524+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
