[2025-04-11T01:24:37.675+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-11T01:24:37.693+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.data_storing scheduled__2025-04-10T00:00:00+00:00 [queued]>
[2025-04-11T01:24:37.703+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.data_storing scheduled__2025-04-10T00:00:00+00:00 [queued]>
[2025-04-11T01:24:37.704+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2025-04-11T01:24:37.716+0000] {taskinstance.py:2879} INFO - Executing <Task(_PythonDecoratedOperator): data_storing> on 2025-04-10 00:00:00+00:00
[2025-04-11T01:24:37.725+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=113) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-11T01:24:37.728+0000] {standard_task_runner.py:72} INFO - Started process 116 to run task
[2025-04-11T01:24:37.726+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'data_storing', 'scheduled__2025-04-10T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/dag_for_workshop.py', '--cfg-path', '/tmp/tmp_br41pld']
[2025-04-11T01:24:37.729+0000] {standard_task_runner.py:105} INFO - Job 10: Subtask data_storing
[2025-04-11T01:24:37.780+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_dag.data_storing scheduled__2025-04-10T00:00:00+00:00 [running]> on host ebadb61ea72f
[2025-04-11T01:24:37.864+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='example@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='data_storing' AIRFLOW_CTX_EXECUTION_DATE='2025-04-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-10T00:00:00+00:00'
[2025-04-11T01:24:37.865+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-11T01:24:37.869+0000] {etl.py:90} ERROR - Error storing data locally: the JSON object must be str, bytes or bytearray, not NoneType
[2025-04-11T01:24:37.870+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-11T01:24:37.878+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-11T01:24:37.879+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=data_storing, run_id=scheduled__2025-04-10T00:00:00+00:00, execution_date=20250410T000000, start_date=20250411T012437, end_date=20250411T012437
[2025-04-11T01:24:37.904+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2025-04-11T01:24:37.920+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-11T01:24:37.923+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
