[2025-04-11T03:10:39.918+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-11T03:10:39.936+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.data_merging scheduled__2025-04-10T00:00:00+00:00 [queued]>
[2025-04-11T03:10:39.946+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.data_merging scheduled__2025-04-10T00:00:00+00:00 [queued]>
[2025-04-11T03:10:39.948+0000] {taskinstance.py:2856} INFO - Starting attempt 8 of 9
[2025-04-11T03:10:39.960+0000] {taskinstance.py:2879} INFO - Executing <Task(_PythonDecoratedOperator): data_merging> on 2025-04-10 00:00:00+00:00
[2025-04-11T03:10:39.969+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1471) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-11T03:10:39.972+0000] {standard_task_runner.py:72} INFO - Started process 1473 to run task
[2025-04-11T03:10:39.971+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'data_merging', 'scheduled__2025-04-10T00:00:00+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/dag_for_workshop.py', '--cfg-path', '/tmp/tmp2kximxn9']
[2025-04-11T03:10:39.975+0000] {standard_task_runner.py:105} INFO - Job 43: Subtask data_merging
[2025-04-11T03:10:40.028+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_dag.data_merging scheduled__2025-04-10T00:00:00+00:00 [running]> on host c97e2588350c
[2025-04-11T03:10:40.980+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='example@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='data_merging' AIRFLOW_CTX_EXECUTION_DATE='2025-04-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='8' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-10T00:00:00+00:00'
[2025-04-11T03:10:40.981+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-11T03:10:41.650+0000] {merge.py:91} INFO - Starting dataset merge.
[2025-04-11T03:10:41.651+0000] {merge.py:92} INFO - Initial Spotify dataset has 81343 rows and 14 columns.
[2025-04-11T03:10:41.652+0000] {merge.py:93} INFO - Initial Grammys dataset has 4771 rows and 6 columns.
[2025-04-11T03:10:41.823+0000] {merge.py:107} INFO - Spotify API dataset has 2689 rows and 8 columns.
[2025-04-11T03:10:41.950+0000] {merge.py:141} ERROR - An error occurred during the merge process: 'is_winner'
[2025-04-11T03:10:41.962+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-11T03:10:41.972+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-11T03:10:41.972+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=data_merging, run_id=scheduled__2025-04-10T00:00:00+00:00, execution_date=20250410T000000, start_date=20250411T031039, end_date=20250411T031041
[2025-04-11T03:10:42.033+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2025-04-11T03:10:42.056+0000] {taskinstance.py:3891} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2025-04-11T03:10:42.059+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
