[2025-04-11T03:35:43.281+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-11T03:35:43.295+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.data_merging scheduled__2025-04-10T00:00:00+00:00 [queued]>
[2025-04-11T03:35:43.304+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.data_merging scheduled__2025-04-10T00:00:00+00:00 [queued]>
[2025-04-11T03:35:43.305+0000] {taskinstance.py:2856} INFO - Starting attempt 11 of 12
[2025-04-11T03:35:43.317+0000] {taskinstance.py:2879} INFO - Executing <Task(_PythonDecoratedOperator): data_merging> on 2025-04-10 00:00:00+00:00
[2025-04-11T03:35:43.325+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1835) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-11T03:35:43.329+0000] {standard_task_runner.py:72} INFO - Started process 1837 to run task
[2025-04-11T03:35:43.327+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'data_merging', 'scheduled__2025-04-10T00:00:00+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/dag_for_workshop.py', '--cfg-path', '/tmp/tmp4ggysz4q']
[2025-04-11T03:35:43.331+0000] {standard_task_runner.py:105} INFO - Job 54: Subtask data_merging
[2025-04-11T03:35:43.382+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_dag.data_merging scheduled__2025-04-10T00:00:00+00:00 [running]> on host c97e2588350c
[2025-04-11T03:35:44.255+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='example@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='data_merging' AIRFLOW_CTX_EXECUTION_DATE='2025-04-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='11' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-10T00:00:00+00:00'
[2025-04-11T03:35:44.256+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-11T03:35:44.920+0000] {merge.py:91} INFO - Starting dataset merge.
[2025-04-11T03:35:44.921+0000] {merge.py:92} INFO - Initial Spotify dataset has 81343 rows and 14 columns.
[2025-04-11T03:35:44.921+0000] {merge.py:93} INFO - Initial Grammys dataset has 4771 rows and 6 columns.
[2025-04-11T03:35:45.068+0000] {merge.py:107} INFO - Spotify API dataset has 2689 rows and 8 columns.
[2025-04-11T03:35:45.112+0000] {merge.py:142} ERROR - An error occurred during the merge process: 'artist_name_clean'
[2025-04-11T03:35:45.124+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-11T03:35:45.134+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-11T03:35:45.135+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=data_merging, run_id=scheduled__2025-04-10T00:00:00+00:00, execution_date=20250410T000000, start_date=20250411T033543, end_date=20250411T033545
[2025-04-11T03:35:45.193+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2025-04-11T03:35:45.216+0000] {taskinstance.py:3891} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2025-04-11T03:35:45.219+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
